### ISSUE TITLE
error tracking

### ISSUE THREAD

**Issue by fponticelli** [asciiascetic/farcek#2]
Really cool lib, do you plan to support error tracking? That would imply to change the return type `Option` to some other container I guess. It would be really nice though.

**Comment by asciiascetic** [comment]
Thanks for the interest!

Implicitly, an error is signalled by the return of an empty array.  This makes it easy to return multiple results from a parse in the case of ambiguous grammars.  Right now the package doesn't take advantage of that potential, but it should in the future.  

I would like to add rewind/retry capabilities so that partially consumed input can be added back to the stream for alternate parsing.  Parsec does this with things like `try` and `lookAhead`.  This might be closer to what you want.

In general I'd like to fill the package out a bit. I wrote it last week for use in another project, but separated it from that project with the intention to enrich the library when I get the time.

**Comment by fponticelli** [comment]
I will keep a close eye on new developments ;)

**Comment by asciiascetic** [comment]
I'm marking this issue as closed (for now).  I added the `Parser.strict` method that will throw a `ParseError(s : String)` when a particular parser outputs no results, where `s` is the offending string.  So, assuming that some of your input string has already been consumed, getting `s` out should be useful.
